/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailRouteImport } from './routes/email'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as ApiDiarizeRouteImport } from './routes/api/diarize'
import { Route as ApiReportRouteImport } from './routes/api/report'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ClienteThreadIdRouteImport } from './routes/cliente.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiarizeRoute = ApiDiarizeRouteImport.update({
  id: '/api/diarize',
  path: '/api/diarize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportRoute = ApiReportRouteImport.update({
  id: '/api/report',
  path: '/api/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteThreadIdRoute = ClienteThreadIdRouteImport.update({
  id: '/cliente/$threadId',
  path: '/cliente/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email': typeof EmailRoute
  '/faq': typeof FaqRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/diarize': typeof ApiDiarizeRoute
  '/api/report': typeof ApiReportRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/cliente/$threadId': typeof ClienteThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email': typeof EmailRoute
  '/faq': typeof FaqRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/diarize': typeof ApiDiarizeRoute
  '/api/report': typeof ApiReportRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/cliente/$threadId': typeof ClienteThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/email': typeof EmailRoute
  '/faq': typeof FaqRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/diarize': typeof ApiDiarizeRoute
  '/api/report': typeof ApiReportRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/cliente/$threadId': typeof ClienteThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email'
    | '/faq'
    | '/api/coach'
    | '/api/diarize'
    | '/api/report'
    | '/api/transcribe'
    | '/cliente/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email'
    | '/faq'
    | '/api/coach'
    | '/api/diarize'
    | '/api/report'
    | '/api/transcribe'
    | '/cliente/$threadId'
  id:
    | '__root__'
    | '/'
    | '/email'
    | '/faq'
    | '/api/coach'
    | '/api/diarize'
    | '/api/report'
    | '/api/transcribe'
    | '/cliente/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailRoute: typeof EmailRoute
  FaqRoute: typeof FaqRoute
  ApiCoachRoute: typeof ApiCoachRoute
  ApiDiarizeRoute: typeof ApiDiarizeRoute
  ApiReportRoute: typeof ApiReportRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ClienteThreadIdRoute: typeof ClienteThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diarize': {
      id: '/api/diarize'
      path: '/api/diarize'
      fullPath: '/api/diarize'
      preLoaderRoute: typeof ApiDiarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report': {
      id: '/api/report'
      path: '/api/report'
      fullPath: '/api/report'
      preLoaderRoute: typeof ApiReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/$threadId': {
      id: '/cliente/$threadId'
      path: '/cliente/$threadId'
      fullPath: '/cliente/$threadId'
      preLoaderRoute: typeof ClienteThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailRoute: EmailRoute,
  FaqRoute: FaqRoute,
  ApiCoachRoute: ApiCoachRoute,
  ApiDiarizeRoute: ApiDiarizeRoute,
  ApiReportRoute: ApiReportRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ClienteThreadIdRoute: ClienteThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
